### ISSUE TITLE
[TBD][ALGEBRA] Implement Matrix struct and its operations

### ISSUE THREAD

**Issue by FoodChain1028** [lattice-complete/Lazarus#9]
## Description

Implement a Matrix structure that represent the Matrix $A$, $B$, $C$ and $D$  in the paper.

## TODOs

- [ ] Implement a matrix structure (this is a `vector of vector`)
    - [ ] `M.row(int)` which returns the value of row[i]
    - [ ] `M.col(int)` which returns the value of col[i]
- [ ] Implement matrix operations with other structure
    - [ ] Matrix * Matrix
    - [ ] Matrix * polynomial_ring_vector  
    - [ ] Matrix * scalar
